@startuml
' use strict UML mode
skinparam style strictuml

actor "User" as user

participant "MainClass" as main <<main>>
main++

create "MainMenu" as menu <<dialog>>
main -> menu : construct
main -> menu : setVisible(true)

user -> menu : click 'Add Product'

create "Product Editor" as editor <<dialog>>
menu -> editor : construct
user -> editor++ : enter details
editor--
user -> editor++ : click 'Save'

create "Product DAO" as dao <<dao>>
editor -> dao : construct

create "Product" as product <<product>>
editor -> product : construct
editor -> editor : gets details
editor -> product : saves details

editor -> dao : save product

editor -> editor : dispose
destroy editor

@enduml
