@startuml
' use strict UML mode
skinparam style strictuml

actor "User" as user

participant "MainClass" as main <<main>>
main++

create "MainMenu" as menu <<dialog>>
main -> menu : construct
main -> menu : setVisible(true)

user -> menu : click 'Add Product'

create "Product Editor" as editor <<dialog>>
menu -> editor : construct
user -> editor++ : selects Category


create "Product DAO" as dao <<dao>>
editor -> dao : gets DAO
editor--

create "Product" as product <<product>>
dao -> product : getProductfromID(); 

dao -> editor : returns Details

user -> editor++ : clicks 'Close'
editor -> editor : dispose
destroy editor

@enduml
