@startuml
' use strict UML mode
skinparam style strictuml

actor "User" as user


participant "MainClass" as main <<main>>
main++

create "MainMenu" as menu <<dialog>>
main -> menu : construct
main -> menu : setVisible(true)

user -> menu : click 'View Products

create "Product Viewer" as viewer <<dialog>>
menu -> viewer : construct


participant "Product DAO" as dao <<dao>>
dao -> viewer++ : list products

participant "Product" as product <<product>>

product -> viewer-- : list infomation
viewer--

user -> viewer++ : click 'Close'
viewer -> viewer : dispose
destroy viewer

@enduml
